### ISSUE TITLE
Email provider not displayed inside the admin panel

### ISSUE THREAD

**Issue by florian-renfer** [adechassey/strapi-provider-email-azure#1]
## Expected Behavior

After configuring the plugin as mail provider inside `/config/plugins.ts` the changes made to the configuration are reflected inside the admin panel.

## Actual Behavior

After configuring the plugin as mail provider inside `/config/plugins.ts` the changes made to the configuration are not reflected inside the admin panel.

Meaning it still shows the pre-confiured provider (sendmail) as well as the pre-configured values for the email addresses.

Out of curiosity I tried to send a test mail from two different networks and public IP addresses and received an error stating the IP address used is listed on `spamhaus.org`. For now I can't tell if this is related to the provider because I assume Strapi.io still tries to use the default configuration.

##### Configuration

```typescript
module.exports = ({ env }) => ({
  email: {
    provider: "strapi-provider-email-microsoft-graph",
    providerOptions: {
      tenantId: env("MICROSOFT_GRAPH_TENANT_ID"),
      clientId: env("MICROSOFT_GRAPH_CLIENT_ID"),
      clientSecret: env("MICROSOFT_GRAPH_CLIENT_SECRET"),
    },
    settings: {
      defaultFrom: "no-reply@example.com",
      defaultReplyTo: "support@example.com",
      defaultApiSender: "api@example.com",
    },
  },
});
```

## Steps to Reproduce the Problem

  1. Install the plugin
  2. Update `/config/plugins.ts` 
  3. Re-build docker image (optional, in case you're using docker recommended)
  4. Start docker container with new image (optional, in case you're using docker recommended)
  5. Go to `http://localhost:1337/admin/settings/email`
  6. Check the values for the email provider configured and email addresses

## Specifications

  - Version: 1.0.2
  - Platform: MacOs
  - Subsystem: Docker Compose (to run PostgreSQL)

**Comment by maierj** [comment]
@florian-renfer I had the same issue and realized that the configuration example in the README.md is wrong: it misses the key `config` i.e. misses a level in the object hierarchy. Compare https://docs.strapi.io/dev-docs/providers#configuring-providers. Provider is showing in admin panel and sending mails after this change.

**Comment by adechassey** [comment]
Hello @florian-renfer,
Thanks for using this plugin and creating an issue.
@maierj, [PR merged](https://github.com/adechassey/strapi-provider-email-microsoft-graph/pull/2) 👍 
Please reopen this issue if your problem persists.
